version: '3.9'
networks:
  TypescriptReact-dev:
    driver: bridge
services:
  app:
    container_name: TypescriptReact
    build:
      context: .
      dockerfile: ./TypescriptReact/Dockerfile
    ports:
      - "80:80"
    networks:
      - TypescriptReact-dev
    depends_on:
      - db
  db: 
    container_name: geropharmdb
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    image: postgres:14.3-alpine
    networks:
      - TypescriptReact-dev