version: '3.9'

services:
  db_auth: 
    container_name: geropharmdb
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    image: postgres:14.3-alpine